### PR TITLE
Make a markdown version of the challenge information

### LINKED ISSUE #1: docx? Seriously?
...

### PR DESCRIPTION
**Pull request by zackpollard**

### CODE REVIEW

**Comment by zackpollard** [comment]
Fixes #1

**Review by Clete2 — CHANGES_REQUESTED** [review]
Please remove the ~$ docx file.

**Comment by zackpollard** [comment]
Removed the temporary file

**Comment by Clete2** [comment]
Thank you!

**Comment by zackpollard** [comment]
Seems a few of the bullet points are messed up, trying to fix

**Comment by Clete2** [comment]
I was not seeing any issues at first glance. Then again, we are doing other things behind the scenes and I didn't dedicate a ton of time to it. If you have more to fix, open a new PR and I will merge it.

Make sure to rebase or merge against the latest from upstream, as I made some other changes.

**Pull request merged**
